[project]
name = "fair-psgg"
version = "1.0.0"
description = "Official implementation of our paper 'A Fair Ranking and New Model for Panoptic Scene Graph Generation', accepted at ECCV 2024"
authors = [{name = "Julian Lorenz", email = "julian.lorenz@uni-a.de"}]
license = "MIT"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "h5py>=3.15.1",
    "numpy>=2.3.4",
    "pandas>=2.3.3",
    "pillow>=12.0.0",
    "pydantic>=2.12.4",
    "scikit-learn>=1.7.2",
    "tensorboard>=2.20.0",
    "timm>=1.0.22",
    "torch>=2.9.0",
    "torchvision>=0.24.0",
    "tqdm>=4.67.1",
    "transformers>=4.57.2",
]
